version: '2.4'
services:

  ui:
    environment:
      - NODE_ENV=qa

  backend:
    environment:
      - ANOTEA_LOG_TYPE=json
      - ANOTEA_MONGODB_URI=mongodb://mongodb:27017/anotea?w=1
      - ANOTEA_SMTP_HOST=smtp
      - ANOTEA_SMTP_PORT=1025

  mongodb:
    image: mongo:4.2.2-bionic
    container_name: anotea_mongodb
    command: --storageEngine=ephemeralForTest --wiredTigerCacheSizeGB 1

  smtp:
    image: rwgrim/docker-noop
