version: '2.4'
services:

  nginx:
    image: anotea_nginx
    container_name: anotea_nginx
    build:
      context: misc/docker/nginx
    ports:
      - 80:80
    mem_limit: 64m
    depends_on:
      - backend
      - ui

  ui:
    image: anotea_ui
    container_name: anotea_ui
    build:
      context: ui
    mem_limit: 32m
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    

  backend:
    image: anotea_backend
    container_name: anotea_backend
    build:
      context: backend
    mem_limit: 1g
    depends_on:
      - mongodb
