const REGIONS = [
    { region : "Auvergne-Rhône-Alpes", dept_num : "3", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "7", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "15", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "26", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "43", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "74", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "38", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "1", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "42", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "63", region_num : "2" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "73", region_num : "2" },
    { region : "Bourgogne-Franche-Comté", dept_num : "21", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "25", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "39", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "58", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "71", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "90", region_num : "3" },
    { region : "Bourgogne-Franche-Comté", dept_num : "89", region_num : "3" },
    { region : "Bretagne", dept_num : "22", region_num : "4" },
    { region : "Bretagne", dept_num : "29", region_num : "4" },
    { region : "Bretagne", dept_num : "35", region_num : "4" },
    { region : "Bretagne", dept_num : "56", region_num : "4" },
    { region : "Bourgogne-Franche-Comté", dept_num : "70", region_num : "3" },
    { region : "Centre-Val de Loire", dept_num : "28", region_num : "5" },
    { region : "Centre-Val de Loire", dept_num : "36", region_num : "5" },
    { region : "Centre-Val de Loire", dept_num : "37", region_num : "5" },
    { region : "Centre-Val de Loire", dept_num : "41", region_num : "5" },
    { region : "Centre-Val de Loire", dept_num : "45", region_num : "5" },
    { region : "Centre-Val de Loire", dept_num : "18", region_num : "5" },
    { region : "Corse", dept_num : "20", region_num : "6" },
    { region : "Grand Est", dept_num : "68", region_num : "7" },
    { region : "Grand Est", dept_num : "8", region_num : "7" },
    { region : "Grand Est", dept_num : "10", region_num : "7" },
    { region : "Grand Est", dept_num : "52", region_num : "7" },
    { region : "Grand Est", dept_num : "67", region_num : "7" },
    { region : "Grand Est", dept_num : "51", region_num : "7" },
    { region : "Grand Est", dept_num : "54", region_num : "7" },
    { region : "Grand Est", dept_num : "55", region_num : "7" },
    { region : "Grand Est", dept_num : "88", region_num : "7" },
    { region : "Grand Est", dept_num : "57", region_num : "7" },
    { region : "Guyane", dept_num : "973", region_num : "9" },
    { region : "Hauts-de-France", dept_num : "2", region_num : "10" },
    { region : "Guadeloupe", dept_num : "971", region_num : "8" },
    { region : "Hauts-de-France", dept_num : "59", region_num : "10" },
    { region : "Hauts-de-France", dept_num : "62", region_num : "10" },
    { region : "Hauts-de-France", dept_num : "60", region_num : "10" },
    { region : "Ile De France", dept_num : "91", region_num : "11", "codeFinanceur" : "2" },
    { region : "Hauts-de-France", dept_num : "80", region_num : "10" },
    { region : "Ile De France", dept_num : "92", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "75", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "93", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "77", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "95", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "94", region_num : "11", "codeFinanceur" : "2" },
    { region : "Ile De France", dept_num : "78", region_num : "11", "codeFinanceur" : "2" },
    { region : "La Réunion-Mayotte", dept_num : "974", region_num : "12" },
    { region : "La Réunion-Mayotte", dept_num : "976", region_num : "12" },
    { region : "Martinique", dept_num : "972", region_num : "13" },
    { region : "Normandie", dept_num : "14", region_num : "14" },
    { region : "Normandie", dept_num : "27", region_num : "14" },
    { region : "Normandie", dept_num : "27", region_num : "14" },
    { region : "Normandie", dept_num : "50", region_num : "14" },
    { region : "Normandie", dept_num : "76", region_num : "14" },
    { region : "Nouvelle-Aquitaine", dept_num : "19", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "16", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "17", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "23", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "79", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "24", region_num : "15" },
    { region : "Normandie", dept_num : "61", region_num : "14" },
    { region : "Nouvelle-Aquitaine", dept_num : "24", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "33", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "87", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "40", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "47", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "64", region_num : "15" },
    { region : "Nouvelle-Aquitaine", dept_num : "86", region_num : "15" },
    { region : "Occitanie", dept_num : "32", region_num : "16" },
    { region : "Occitanie", dept_num : "9", region_num : "16" },
    { region : "Occitanie", dept_num : "11", region_num : "16" },
    { region : "Occitanie", dept_num : "12", region_num : "16" },
    { region : "Occitanie", dept_num : "30", region_num : "16" },
    { region : "Occitanie", dept_num : "31", region_num : "16" },
    { region : "Occitanie", dept_num : "34", region_num : "16" },
    { region : "Occitanie", dept_num : "65", region_num : "16" },
    { region : "Occitanie", dept_num : "46", region_num : "16" },
    { region : "Occitanie", dept_num : "48", region_num : "16" },
    { region : "Occitanie", dept_num : "66", region_num : "16" },
    { region : "Occitanie", dept_num : "81", region_num : "16" },
    { region : "Occitanie", dept_num : "82", region_num : "16" },
    { region : "Pays de Loire", dept_num : "44", region_num : "17" },
    { region : "Pays de Loire", dept_num : "53", region_num : "17" },
    { region : "Pays de Loire", dept_num : "49", region_num : "17" },
    { region : "Pays de Loire", dept_num : "85", region_num : "17" },
    { region : "Pays de Loire", dept_num : "72", region_num : "17" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "4", region_num : "18" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "13", region_num : "18" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "6", region_num : "18" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "83", region_num : "18" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "84", region_num : "18" },
    { region : "Provence Alpes Côte d'Azur", dept_num : "5", region_num : "18" },
    { region : "St Pierre et Miquelon", dept_num : "975", region_num : "19" },
    { region : "Auvergne-Rhône-Alpes", dept_num : "69", region_num : "2" },
    { region : "Aquitaine", dept_num : "33", region_num : "1" },
    { region : "La Réunion-Mayotte", dept_num : "978", region_num : "12" },
];

export default REGIONS;
